mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('need.urls', namespace='need')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

]

need/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^new/$', views.new, name='new'),
	url(r'^(?P<pk>[0-9]+)/done$', views.done, name='done'),
	url(r'^(?P<pk>[0-9]+)/delete$', views.delete, name='delete'),
	url(r'^langchoice$', views.langchoice, name='langchoice'),
	url(r'^about/$', views.about, name='about'),
	url(r'^need/(?P<pk>[0-9]+)/transl/$', views.add_transl, name='add_transl'),
	url(r'^need/(?P<pk>[0-9]+)/transl/remove$', views.remove_transl, name='remove_transl'),
]

need/models.py
from django.db import models
import datetime
from django.utils import timezone

class Need(models.Model):
	what = models.CharField(max_length=200)
	amount = models.PositiveSmallIntegerField(default=1)
	# old way of choosing place
#	where = models.CharField(max_length=200)
	# new way of choosing place
	PLACES = (('H', 'HWBR'), ('E', 'Emporhalle'), ('P', 'Physik'),)
	where = models.CharField(max_length=1, choices=PLACES, default='H')
	pub_date = models.DateTimeField('date published')
	done = models.BooleanField(default=False)
	
	def __str__(self):
		return "%d %s needed at %s" % (self.amount, self.what, self.where)

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		
	def public_transl(self):
		return self.transl.filter(public=True)

class Transl(models.Model):
	need = models.ForeignKey('need.Need', related_name='transl')
#	author = models.CharField(max_length=200)
#	text = models.TextField()
	text = models.CharField(max_length=200)
	created_date = models.DateTimeField(default=timezone.now)
	public = models.BooleanField(default=False)

	def publish(self):
		self.public = True
		self.save()
		
	def hide(self):
		self.public = False
		self.save()

	def __str__(self):
		return self.text

need/forms.py
from django import forms

from .models import Need, Transl

class NeedForm(forms.ModelForm):

    class Meta:
        model = Need
        fields = ('what', 'amount', 'where')

class TranslForm(forms.ModelForm):

    class Meta:
        model = Transl
        fields = ('text',)

need/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.utils.translation import get_language, get_language_info
from django.contrib.auth.decorators import login_required

from .models import Need, Transl
from .forms import NeedForm, TranslForm

def index(request):
    latest_need_list = Need.objects.order_by('-pub_date')[:50]
    return render(request, 'need/index.html', {'latest_need_list': latest_need_list})

#def index(request):
#	# Translators: This message appears on the index page
#	output = _("Hello")
#	return HttpResponse(output)

def detail(request, pk):
	need = get_object_or_404(Need, pk=pk)
	return render(request, 'need/detail.html', {'need': need})
	
def new(request):
	if request.method == "POST":
		print(request)
		form = NeedForm(request.POST)
		if form.is_valid():
			print("valid")
			need = form.save(commit=False)
			need.pub_date = timezone.now()
			need.save()
			return HttpResponseRedirect(reverse('need:index'))
		else:
			print("not valid")
			form = NeedForm()
			# Translators: This error message appears on the new need form page
			return render(request, 'need/new.html', {'error_message': _("wrong input"), 'form': form})
	form = NeedForm()
	return render(request, 'need/new.html', {'form': form})
	
def done(request, pk):
	need = get_object_or_404(Need, pk=pk)
	need.done = True
	need.save()
	return HttpResponseRedirect(reverse('need:index'))

@login_required	
def delete(request, pk):
	need = get_object_or_404(Need, pk=pk)
	need.delete()
	return HttpResponseRedirect(reverse('need:index'))
	
def langchoice(request):
	referer = request.META["HTTP_REFERER"]
	ar = get_language_info('ar')
	#fa = get_language_info('fa')
	de = get_language_info('de')
	en = get_language_info('en')
	languages = [ar, de, en] #fa,
	return render(request, 'need/langchoice.html', {'languages': languages, 'referer': referer})
	
def about(request):
	return render(request, 'need/about.html', {})
	
def add_transl(request, pk):	
    need = get_object_or_404(Need, pk=pk)
    if request.method == "POST":
        form = TranslForm(request.POST)
        if form.is_valid():
            transl = form.save(commit=False)
            transl.need = need
            transl.publish()
            transl.save()
            return redirect('need:detail', pk=need.pk)
    else:
        form = TranslForm()
    return render(request, 'need/add_transl.html', {'form': form, 'need': need})

@login_required	
def remove_transl(request, pk):
	transl = get_object_or_404(Transl, pk=pk)
	transl.hide()
	return redirect('need:detail', pk=transl.need.pk)

need/templates/need/about.html
{% extends 'need/base.html' %}
{% load i18n %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-3">

	</div>
	<div class="col-xs-12 col-md-6">
		<p class="text-center">
			{% blocktrans %}
			This is just a tiny tool. Maybe it can help.
			{% endblocktrans %}

			{% endblock content %}
		</p>
	</div>
	<div class="col-xs-12 col-md-3">

	</div>
</div>

need/templates/need/add_transl.html
{% extends "need/base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-3">

	</div>
	<div class="col-xs-12 col-md-6">

		<div class="well">
			<div class="date">{{ need.pub_date }}</div>
			{% if need.done %}
				<p>{% trans "status" %} = {% trans "done" %}</p>
			{% else %}
				<p><a class="btn btn-success" href="{% url 'need:done' pk=need.pk  %}">{% trans "Got it!" %}</a></p>
			{% endif %}	
			{% get_current_language_bidi as LANGUAGE_BIDI %}
			{% if LANGUAGE_BIDI %}
				<p>{{ need.what }} = {% trans "what" %}</p>
				<p>{{ need.amount }} = {% trans "amount" %}</p>
				<p>{{ need.get_where_display }} = {% trans "where" %}</p>
			{% else %}
				<p>{% trans "what" %} = {{ need.what }}</p>
				<p>{% trans "amount" %} = {{ need.amount }}</p>
				<p>{% trans "where" %} = {{ need.get_where_display }}</p>
			{% endif %}
		</div>
		
		<h3>{% trans "translate" %}</h3>
	
		<form method="POST" class="post-form">{% csrf_token %}
			<p>
				<label for="id_text" class="sr-only">{% trans "what" %}:</label>
				<input id="id_text" maxlength="200" name="text" type="text" class="form-control" placeholder="{% trans "what" %}" required autofocus />
			</p>
			<button type="submit" class="save btn btn-default">{% trans "Save" %}</button>
		</form>
	
	</div>
	<div class="col-xs-12 col-md-3">

	</div>
</div>
{% endblock %}

need/templates/need/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="What do you need?">
	<meta name="author" content="need">
	<link rel="icon" href="{% static 'need/img/favicon.ico' %}">
	<title>need</title>
	<link rel="stylesheet" href="{% static 'need/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'need/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" href="{% static 'need/css/style.css' %}">
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<!--
				<a class="navbar-brand" href="/">need</a>
				-->
				<a class="navbar-brand" href="{% url 'need:new' %}"><span class="glyphicon glyphicon-plus"></span> {% trans "Add a need" %}</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'need:index' %}">{% trans "List" %}</a></li>
					<li><a href="{% url 'need:langchoice' %}">زبان / لغة / DE / EN</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'need:about' %}">{% trans "About" %}</a></li>
					<!--<li><a href="/admin"><span class="glyphicon glyphicon-wrench"></span></a></li>-->
					<!--
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-pencil"></span> Sign up<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li class="dropdown-header">Sign up as ...</li>
							<li class="divider"></li>
							<li><a href="{% url 'need:index' %}">Chair</a></li>
							<li class="divider"></li>
							<li><a href="{% url 'need:index' %}">Jobber</a></li>
							<li class="divider"></li>
						</ul>
					</li>
					-->
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>

	<script src="{% static 'need/js/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'need/js/bootstrap.min.js' %}"></script>
</body>
</html>

need/templates/need/detail.html
{% extends 'need/base.html' %}
{% load i18n %}

{% block content %}

<div class="row">
	<div class="col-xs-12 col-md-3">

	</div>
	<div class="col-xs-12 col-md-6">
  		<div class="well">
  			<div class="date">{{ need.pub_date }}</div>
			{% if need.done %}
				<p>{% trans "status" %} = {% trans "done" %}</p>
			{% else %}
				<p><a class="btn btn-success" href="{% url 'need:done' pk=need.pk  %}">{% trans "Got it!" %}</a></p>
			{% endif %}
			
			{% get_current_language_bidi as LANGUAGE_BIDI %}
			{% if LANGUAGE_BIDI %}
				<p>{{ need.what }} = {% trans "what" %}</p>
				<p>{{ need.amount }} = {% trans "amount" %}</p>
				<p>{{ need.get_where_display }} = {% trans "where" %}</p>
			{% else %}
				<p>{% trans "what" %} = {{ need.what }}</p>
				<p>{% trans "amount" %} = {{ need.amount }}</p>
				<p>{% trans "where" %} = {{ need.get_where_display }}</p>
			{% endif %}
			
			{% if user.is_superuser %}
				<!-- Single button -->
				<div class="btn-group text-center">
					<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-trash"></span></button>
					<ul class="dropdown-menu" role="menu">
						<li class="dropdown-header">{% trans "Are you sure?" %}</li>
						<li class="divider"></li>
						<li><a href="{% url 'need:delete' pk=need.pk %}">{% trans "Yes" %}</a></li>
						<li class="divider"></li>
						<li><a href="#">{% trans "No" %}</a></li>
						<li class="divider"></li>
					</ul>
				</div>
			{% else %}
		
			{% endif %}
			<hr>
			<a class="btn btn-info" href="{% url 'need:add_transl' pk=need.pk %}">{% trans "Add translation" %}</a>
			{% for transl in need.transl.all %}
				{% if transl.public %}
					<div class="transl">
						<div class="date">{{ transl.created_date }}</div>
						{% if user.is_superuser %}
							<a class="btn btn-warning" href="{% url 'need:remove_transl' pk=transl.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
						{% else %}

						{% endif %}
						<strong>#{{ transl.id }}</strong>
						<p>{{ transl.text|linebreaks }}</p>						
					</div>
				{% else %}
				
				{% endif %}
			{% empty %}
				
			{% endfor %}
		</div>		
	</div>
	<div class="col-xs-12 col-md-3">
    
	</div>
</div>



{% endblock content %}

need/templates/need/index.html
{% extends 'need/base.html' %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col-xs-12 col-md-3">
    
  </div>
  <div class="col-xs-12 col-md-6">
  
    {% if latest_need_list %}
		{% for need in latest_need_list %}			
			{% if need.done %}
	    	<div class="alert alert-success" role="alert">
	    	{% else %}
	    	<div class="alert alert-info" role="alert">
	    	{% endif %}
	    		<div class="row">
		    		<a href="{% url 'need:detail' need.id %}">	    		
						<div class="col-xs-8 col-md-8">
							{% get_current_language_bidi as LANGUAGE_BIDI %}
							{% if LANGUAGE_BIDI %}
								({{ need.amount }}={% trans "amount" %}) {{ need.what }}
								<br>
								{{ need.get_where_display }}={% trans "where" %}
								<br>
								{{ need.pub_date }}
								<br>
								{{ need.public_transl.count }}={% trans "Translations" %}
							{% else %}
								{{ need.what }} ({% trans "amount" %}={{ need.amount }})
								<br>
								{% trans "where" %}={{ need.get_where_display }}
								<br>
								{{ need.pub_date }}
								<br>
								{% trans "Translations" %}={{ need.public_transl.count }}
							{% endif %}
						</div>
					</a>
					<div class="col-xs-4 col-md-4">
						<div class="text-center">
							{% if need.done %}
							<p><span class="glyphicon glyphicon-check"></span> {% trans "done" %}</p>							
							{% else %}

							{% endif %}
							{% if user.is_superuser %}
							<!-- Single button -->
							<div class="btn-group text-center">
								<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-trash"></span></button>
								<ul class="dropdown-menu" role="menu">
									<li class="dropdown-header">{% trans "Are you sure?" %}</li>
									<li class="divider"></li>
									<li><a href="{% url 'need:delete' pk=need.pk %}">{% trans "Yes" %}</a></li>
									<li class="divider"></li>
									<li><a href="#">{% trans "No" %}</a></li>
									<li class="divider"></li>
								</ul>
							</div>
							{% else %}
						
							{% endif %}
						</div>						
					</div>	
				</div>
			</div>			
		{% endfor %}
	{% else %}
		<p>{% trans "No needs are available." %}</p>
	{% endif %}
  </div>
  
  <div class="col-xs-12 col-md-3">
    
  </div>
</div>
{% endblock content %}

need/templates/need/langchoice.html
{% extends 'need/base.html' %}
{% load i18n %}

{% block content %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ referer }}" />
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Choose" />
</form>

<!--
<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}" />
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Choose" />
</form>
-->

{% endblock content %}

need/templates/need/new.html
{% extends 'need/base.html' %}
{% load i18n %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-1">
		
	</div>
	<div class="col-xs-12 col-md-10">
  
		<div class="container">
		
			<form class="form-signin" method="POST" action="{% url 'need:new' %}">{% csrf_token %}
				<h2 class="form-signin-heading">{% trans "New need" %}</h2>
				
				<label for="id_what" class="sr-only">{% trans "what" %}</label>
				<input id="id_what" maxlength="200" name="what" type="text" class="form-control" placeholder="{% trans "what" %}" required autofocus>
								
				<label for="id_amount" class="sr-only">{% trans "amount" %}</label>
				<input id="id_amount" name="amount" type="number" value="1" min="1" class="form-control" placeholder="{% trans "amount" %}" required>	
				
				<label for="id_where" class="sr-only">{% trans "where" %}</label>
				<select id="id_where" name="where" class="form-control">
					<option value="H" selected="selected">HWBR</option>
					<option value="E">Emporhalle</option>
					<option value="P">Physik</option>
				</select>				
				
				<p></p>
				
				<button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Add" %}</button>
				<input type="hidden" name="next" value="{{ next }}" />
				
				<p></p>
				
				<div class="alert alert-info alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					{% trans "what" %} {% trans "no more than 200 characters." %} 
				</div>
					
				{% if error_message %}
				<div class="alert alert-warning alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  {{ error_message }}
				</div>
				{% endif %}
			</form>	  
		</div>		
	</div>
  
	<div class="col-xs-12 col-md-1">
    
	</div>
</div>
{% endblock content %}